return {
    pde = {
        lua = true,
        rust = true,
        go = false,
        cpp = true,
        python = true,
        html = true,
        typescript = true,
        tailwind = true,
        vuejs = true,
        svelte = true,
        elixir = true,
        yaml = true,
        jupyter = true,
        scala = true,
        julia = true,
        docker = true,
        terraform = true,
        solidity = true,
        kotlin = true,
        json = true,
        markdown = true,
    },
}